### ISSUE TITLE
Update all examples to use the new Pydantic integration

### ISSUE THREAD

**Issue by ParthSareen** [ollama/ollama-python#312]
With the introduction of https://github.com/ollama/ollama-python/pull/276, examples must be updated.

Add appropriate readme updates and create best practices through examples.

**Comment by sprior** [comment]
Is this why I'm getting "Object of type function is not JSON serializable" on the call to chat() in the tools.py example?

**Comment by ParthSareen** [comment]
Hey! Could you drop what version of ollama-python you're on? `pip show ollama`

**Comment by sprior** [comment]
Name: ollama
Version: 0.3.3
Summary: The official Python client for Ollama.
Home-page: https://ollama.ai
Author: Ollama
Author-email: hello@ollama.com
License: MIT
Location: c:\Users\sprio\Documents\Python\ollama-client\.venv\Lib\site-packages
Requires: httpx
Required-by:

**Comment by ParthSareen** [comment]
Got it. @sprior Could you upgrade to the newest version of the sdk? It's 0.4.0.

**Comment by sprior** [comment]
@ParthSareen ok thanks, working now.  Just FYI when I run your examples I seem to have to add client=Client(host='<my host>') or else it can't connect, I'm running Windows Ollama and the Python example in VSCode.  I'm guessing somehow there the default localhost isn't working.  I don't know how common this issue is but maybe make the examples a bit more universal.

**Comment by ParthSareen** [comment]
Thanks for letting me know! Will try to repro :) @sprior
